### ISSUE TITLE
What about primeflex?

### ISSUE THREAD

**Issue by luixal** [primefaces/primevue-quickstart-nuxt3#5]
I've tried to set it up following the steps [in the docs](https://primefaces.org/primevue/showcase/#/primeflex):

I added css in `nuxt.config.ts`:

```js
import { defineNuxtConfig } from 'nuxt3'

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
    css: [
        'primevue/resources/themes/saga-blue/theme.css',
        'primevue/resources/primevue.css',
        'primeicons/primeicons.css',
        'primeflex/primeflex.css'
    ]
})
```
but nothings seems to be loaded as nothing happens when trying to use spacing or elevation.

If I go importing only the `elevation.css`, for example, it complains about SSR:

```

ℹ nuxt.config.ts updated. Restarting nuxt...                                                                                                                                                              10:37:14
ℹ Vite warmed up in 211ms                                                                                                                                                                                 10:37:15

 WARN  [SSR] Error transforming /home/user/dev/habits/node_modules/primeflex/src/_elevation.scss: Undefined mixin.                                                                                     10:37:15
   ╷
13 │ @include style-class('box-shadow', $shadows, true);
   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/primeflex/src/_elevation.scss 13:1  root stylesheet

  ╷
  13 │ @include style-class('box-shadow', $shadows, true);
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/primeflex/src/_elevation.scss 13:1  root stylesheet
  at Object.wrapException (node_modules/sass/sass.dart.js:1246:17)
  at node_modules/sass/sass.dart.js:69198:25
  at _wrapJsFunctionForAsync_closure.$protected (node_modules/sass/sass.dart.js:3729:15)
  at _wrapJsFunctionForAsync_closure.call$2 (node_modules/sass/sass.dart.js:27882:12)
  at Object._asyncStartSync (node_modules/sass/sass.dart.js:3693:20)
  at _EvaluateVisitor2.visitIncludeRule$body$_EvaluateVisitor0 (node_modules/sass/sass.dart.js:69245:16)
  at _EvaluateVisitor2.visitIncludeRule$1 (node_modules/sass/sass.dart.js:69183:19)
  at IncludeRule0.accept$1$1 (node_modules/sass/sass.dart.js:84229:22)
  at IncludeRule0.accept$1 (node_modules/sass/sass.dart.js:84232:19)
  at node_modules/sass/sass.dart.js:68106:43

✔ Vite server built in 813ms             
```

Whether or not I disable ssr (the the first error goes away, logically), it complains when loading:

```
[plugin:vite:css] Undefined mixin.
   ╷
13 │ @include style-class('box-shadow', $shadows, true);
   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/primeflex/src/_elevation.scss 13:1  root stylesheet
/home/users/dev/habits/node_modules/primeflex/src/_elevation.scss:13:1
    at Object.wrapException (/home/user/dev/habits/node_modules/sass/sass.dart.js:1246:17)
    at /home/user/dev/habits/node_modules/sass/sass.dart.js:69198:25
    at _wrapJsFunctionForAsync_closure.$protected (/home/user/dev/habits/node_modules/sass/sass.dart.js:3729:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/home/user/dev/habits/node_modules/sass/sass.dart.js:27882:12)
    at Object._asyncStartSync (/home/user/dev/habits/node_modules/sass/sass.dart.js:3693:20)
    at _EvaluateVisitor2.visitIncludeRule$body$_EvaluateVisitor0 (/home/user/dev/habits/node_modules/sass/sass.dart.js:69245:16)
    at _EvaluateVisitor2.visitIncludeRule$1 (/home/user/dev/habits/node_modules/sass/sass.dart.js:69183:19)
    at IncludeRule0.accept$1$1 (/home/user/dev/habits/node_modules/sass/sass.dart.js:84229:22)
    at IncludeRule0.accept$1 (/home/user/dev/habits/node_modules/sass/sass.dart.js:84232:19)
    at /home/user/dev/habits/node_modules/sass/sass.dart.js:68106:43
```

Any idea how to get this working?

PS: I'm using primeflex@3.1.2, should I use 2.0.0?

**Comment by ccsv** [comment]
Try using this:

```
    css: [
        'primevue/resources/themes/saga-blue/theme.css',
        'primevue/resources/primevue.css',
        'primeicons/primeicons.css',
        'primeflex/primeflex.min.css',
    ],
    build: {
        transpile: ['primevue']
    },
```

in plugins make sure your file has

```
import PrimeVue from 'primevue/config';
 //importyour components

export default defineNuxtPlugin(nuxtApp => {
    nuxtApp.vueApp.use(PrimeVue, { ripple: true })
 //add your components
})
```
