### ISSUE TITLE
500 internal error

### ISSUE THREAD

**Issue by c-myers1** [primefaces/primevue-quickstart-nuxt3#6]
Followed the instructions verbatim and on "yarn dev" I get:

    500
    m.default is not a function
    at file:///C:/Users/user1/dev/primevue/primevue-quickstart-nuxt3/.nuxt/dist/server/server.mjs:10:126
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async renderToString (file:///C:/Users/user1/dev/primevue/primevue-quickstart-nuxt3/node_modules/vue-bundle- 
    renderer/dist/index.mjs:247:19)
    at async renderMiddleware (file:///C:/Users/user1/dev/primevue/primevue-quickstart-nuxt3/.nuxt/nitro/index.mjs:206:20)
    at async handle (file:///C:/Users/user1/dev/primevue/primevue-quickstart-nuxt3/node_modules/h3/dist/index.mjs:601:19)

**Comment by chanthavong** [comment]
## I think is not suport ssr 
if want to use with spa mode can set
```ts
import { defineNuxtConfig } from "nuxt";

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  css: [
    "primevue/resources/themes/saga-blue/theme.css",
    // 'primevue/resources/themes/lara-light-indigo/theme.css',
    "primevue/resources/primevue.css",
    "primeicons/primeicons.css",
  ],
 ssr: false,
});
```

**Comment by aleavikraman** [comment]
you're missing 

build: {
    transpile: ['primevue']
},
